[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-bleak-retry-connector",
	"source": "bleak-retry-connector",
	"version": "3.10.0-2",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-bluetooth-adapters",
		"python3-async-timeout | python3-supported-min (>= 3.11)",
		"python3-dbus-fast",
		"python3:any"
	],
	"installedSize": 85,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "Connector for Bleak Clients that handles transient connection failures",
	"homepage": "https://github.com/bluetooth-devices/bleak-retry-connector",
	"filename": "pool/main/b/bleak-retry-connector/python3-bleak-retry-connector_3.10.0-2_all.deb",
	"size": 26092,
	"md5": "0fcdff70b9db8c5598cfbadf58034341",
	"sha256": "1a85b5aa7cf059030a798b42fa153b418f9706cc4fbb8e62d51fda3aad02633a",
	"descriptionMd5": "94cf3179d80dc95dc44c0b30cf94cbad"
}]