[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pytest-instafail",
	"source": "pytest-instafail",
	"version": "0.4.2-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-pytest",
		"python3:any"
	],
	"suggests": [
		"python-pytest-instafail-doc"
	],
	"installedSize": 34,
	"maintainer": "Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>",
	"description": "plugin for py.test that shows failures and errors instantly",
	"homepage": "https://pypi.python.org/pypi/pytest-instafail",
	"filename": "pool/main/p/pytest-instafail/python3-pytest-instafail_0.4.2-1_all.deb",
	"size": 9320,
	"md5": "ed48b47a12c26f3d681998220e23843f",
	"sha256": "aea2744e64df493e1a8c98f51dd619d687c0be279f617310ca63082b0771e25a",
	"descriptionMd5": "4acabc61b3293224ea4a27802dc75041"
}]