{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-bleak-retry-connector",
	"source": "bleak-retry-connector",
	"version": "3.10.0-3",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-bleak",
		"python3-bluetooth-adapters",
		"python3-async-timeout | python3-supported-min (>= 3.11)",
		"python3-dbus-fast",
		"python3:any"
	],
	"installedSize": 85,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "Connector for Bleak Clients that handles transient connection failures",
	"homepage": "https://github.com/bluetooth-devices/bleak-retry-connector",
	"filename": "pool/main/b/bleak-retry-connector/python3-bleak-retry-connector_3.10.0-3_all.deb",
	"size": 26160,
	"md5": "e33e46d17bfbe87c94360e37bbdfff95",
	"sha256": "03eb3bb50e500d57a33fa652d354692436688646b07c9d05ff845f7c596929f9",
	"descriptionMd5": "94cf3179d80dc95dc44c0b30cf94cbad"
}