[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-bleak-retry-connector",
	"source": "bleak-retry-connector",
	"version": "4.4.3-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-bleak",
		"python3-bluetooth-adapters",
		"python3-async-timeout | python3-supported-min (>= 3.11)",
		"python3-dbus-fast",
		"python3:any"
	],
	"installedSize": 90,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "Connector for Bleak Clients that handles transient connection failures",
	"homepage": "https://github.com/bluetooth-devices/bleak-retry-connector",
	"filename": "pool/main/b/bleak-retry-connector/python3-bleak-retry-connector_4.4.3-1_all.deb",
	"size": 30620,
	"md5": "d9a33e8725d48ae8831cccbc6bc1a155",
	"sha256": "eee1b610e3a414f8696634a8c24ea77e608a79bd02e9b458e17bf11a3246320a",
	"descriptionMd5": "94cf3179d80dc95dc44c0b30cf94cbad"
}]